@startuml version

state Estática
state Básica
state Vista
state Retroalimentación
state Colaborativa

[*] --> Básica
Estática --> Básica:Mantenimiento perfectivo
Básica --> Vista:Mantenimiento adaptativo
Vista --> Retroalimentación:Mantenimiento perfectivo
Retroalimentación --> Colaborativa:Mantenimiento perfectivo
Colaborativa --> [*]

note right of Estática #15D2F3
  Mostrar una malla según una configuración particular
end note

note right of Básica #15D2F3
  Gestiona y corrige hasta tres intentos de 
  cada una de las configuraciones dadas en 
  su configuración inicial (prompt y console.log)
end note

note right of Vista #15D2F3
  Añadiendo la vista con HTML y CSS
end note

note right of Trazabilidad #15D2F3
  Añadiendo registro de soluciones e intentos
  de cada usuario, y generando preguntas falladas,
  nuevas (por combinación de otras, and, or), 
  categorías de complejidad según respuestas, 
  taxonomía de bloom: análisis, síntesis, evaluación, ...
end note

note right of Configurable #15D2F3
  Los usuarios pueden proponer nuevas configuraciones
  acpetadas por el administrador para otros usuarios,
  competiciones en menor tiempo, ...
end note



@enduml